export const els = {
  sky: document.querySelector('#sky'),
  container: document.querySelector('#scene-content'),
  sceneTitle: document.querySelector('#scene-title'),
  sceneNav: document.querySelector('.scene-nav'),
  plantPanel: document.querySelector('.plant-panel'),
  plantName: document.querySelector('#plant-name'),
  plantDescription: document.querySelector('#plant-description'),
  plantAttributes: document.querySelector('#plant-attributes'),
  plantStatus: document.querySelector('#plant-status'),
  panelClose: document.querySelector('.panel-close'),
  loadingIndicator: document.querySelector('.loading-indicator'),
  interactionPanel: document.querySelector('.interaction-panel'),
  interactionClose: document.querySelector('#interaction-close'),
  interactionTitle: document.querySelector('#interaction-title'),
  interactionBody: document.querySelector('#interaction-body'),
  historyPanel: document.querySelector('.history-panel'),
  historyClose: document.querySelector('#history-close'),
  globalQueryControls: document.querySelector('#global-query-controls'),
  comparePanel: document.querySelector('.compare-panel'),
  compareBody: document.querySelector('#compare-body'),
  compareClose: document.querySelector('#compare-close'),
  voiceLog: document.querySelector('#voice-log'),
  hint: document.querySelector('.gesture-hint'),
  disambiguationLayer: document.querySelector('#disambiguation-layer'),
  scene: document.querySelector('#main-scene'),
  camera: document.querySelector('#camera'),
};
